# dataset
root_dir: /home/lzh/datasets/crypto_datasets/BTC_hourly/Binance_BTCUSDT_1hour_aft_preprocess6.csv
history_window: 3
predict_window: 3
profit_limit: 0.02
loss_limit: 0.02

# model params
feature_dim: 6
hidden_dim: 16
output_dim: 1
label_dim: 2

# train params
lr: 0.0001
max_lr: 0.001
epoch: 10
batch_size: 8
momentum: 0.9
weight_decay: 0.0001
print_freq: 1000